# Generated by Django 6.0.4 on 2026-06-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('room', models.CharField(max_length=5)),
            ],
        ),
    ]
